# Generated by Django 4.0.4 on 2022-06-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=70)),
                ('adres', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'klienci',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.BooleanField(choices=[('K', 'Kobieta'), ('M', 'Mezczyzna')])),
                ('birthday', models.DateField(blank=True, null=True)),
                ('role', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, unique=True)),
                ('opis', models.TextField(blank=True, max_length=300, null=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zdjecie', models.ImageField(default='', upload_to='static')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('zasob', models.IntegerField()),
                ('dostepnosc', models.BooleanField(default=True)),
                ('nowy_produkt', models.DateTimeField(auto_now_add=True, verbose_name='dodano produkt')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ap.kategoria')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'produkty',
            },
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_platnosci', models.CharField(max_length=1000)),
                ('zamowienie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ap.orderitem')),
            ],
            options={
                'verbose_name_plural': 'platnosci',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='produkt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ap.produkty'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='Ap.orderitem')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ap.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rabat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nazwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ap.produkty')),
            ],
            options={
                'verbose_name_plural': 'koszyk',
            },
        ),
    ]
