# Generated by Django 4.0.4 on 2022-06-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='zdjecie',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
